CREATE DATABASE WebsiteASPNET;
USE WebsiteASPNET;

CREATE TABLE USER
(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) UNIQUE NOT NULL,
EMAIL VARCHAR(100) UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);